update

diff --git a/nginx/Dockerfile b/nginx/Dockerfile
--- a/nginx/Dockerfile
+++ b/nginx/Dockerfile
@@ -2,10 +2,28 @@ FROM nginx:stable-alpine
 
 ENV NGINX_DIR=/etc/nginx
 
-RUN sed -i 's/dl-cdn.alpinelinux.org/dl-3.alpinelinux.org/g' /etc/apk/repositories && \
-    apk update --no-cache && \
-    apk upgrade --no-cache && \
-    apk add --no-cache openssl
+# Function to retry a command up to 5 times
+RUN retry() { \
+  local n=1; \
+  local max=5; \
+  local delay=5; \
+  while true; do \
+    "$@" && break || { \
+      if [[ $n -lt $max ]]; then \
+        ((n++)); \
+        echo "Command failed. Attempt $n/$max:"; \
+        sleep $delay; \
+      else \
+        echo "The command has failed after $n attempts."; \
+        return 1; \
+      fi; \
+    }; \
+  done; \
+}
+
+RUN retry apk update --no-cache && \
+    retry apk upgrade --no-cache && \
+    retry apk add --no-cache openssl
 
 COPY setup/nginx.conf ${NGINX_DIR}/nginx.conf
 COPY setup/index.html /usr/share/nginx/html/index.html
